### ISSUE TITLE
Pls, comments/docs in English

### ISSUE THREAD

**Issue by reinerotto** [liudf0716/apfree-wifidog#223]
As an intensive user of coova-chilli, I am looking for an alternative, because of performance issues. 
To compare coovas functions, and apfree_wifidogs functionality, and as a general courtesy to the community, it would be very helpful to have complete English comments or docs. 
googles translate is not very helpful :-)

**Comment by liudf0716** [comment]
thanks for your advise, I will try my best to provide more english document.

**Comment by superliu666** [comment]
Hi I am responsible to translate this document and if you have any question or problem please chat with me, 🙏 thanks

**Comment by superliu666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by SohailAsghar236** [comment]
> Hi I am responsible to translate this document and if you have any question or problem please chat with me, 🙏 thanks

Is there a way to translate the app into English? Or an English language setting is available?

**Comment by superliu666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by liudf0716** [comment]
> > Hi I am responsible to translate this document and if you have any question or problem please chat with me, 🙏 thanks
> 
> Is there a way to translate the app into English? Or an English language setting is available?

English language setting is default available.

**Comment by superliu666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
