### ISSUE TITLE
Heybro, how to set the router side for the server, and how to obtain the wwas account and password? 

### ISSUE THREAD

**Issue by boluojiang521** [liudf0716/apfree-wifidog#228]
Heybro, how to set the router side for the server, and how to obtain the wwas account and password? 
请问下路由器这边如何与服务端对接设置，后台账号密码如何获取，文档里没写谢谢
![_20201001113204](https://user-images.githubusercontent.com/51756852/94762552-9b687480-03da-11eb-9c41-2a6d278602c7.png)

**Comment by liudf0716** [comment]
Hi bro, u can try apfree/apfree or wificoin/wificoin. In fact, u can read the code to find truth. good luck
