### ISSUE TITLE
是否支持单网卡运行？是否支持多vlan，

### ISSUE THREAD

**Issue by xiaolongzhou123** [liudf0716/apfree-wifidog#238]
问：是否支持单网卡运行？公司有openwrt做旁路由单网卡，apfree_wifi是否可以在单网口上跑？

问: 是否支持多vlan，是否支持？

**Comment by liudf0716** [comment]
apfree wifidog依赖openwrt的环境，您说的2种场景我没用过，需要验证才能知道。

**Comment by liudf0716** [comment]
目前已经支持
