### ISSUE TITLE
iptables_fw_init()在mangle表初始化完之后，nat和filter都找不到target

### ISSUE THREAD

**Issue by wp1411847064** [liudf0716/apfree-wifidog#239]
iptables_fw_init()在mangle表初始化完之后，nat和filter中新建的chain都找不到，甚至找不到accept等，调换初始化顺序，同样在初始化完第一张表之后，后面两张表的初始化在add或者insert的时候也找不到target

**Comment by wp1411847064** [comment]
fw3_ipt_close(handle)后加上xtables_fini()

**Comment by liudf0716** [comment]
@wp1411847064 能更详细的描述一下吗？什么版本下，有什们问题？

**Comment by wp1411847064** [comment]
> @wp1411847064 能更详细的描述一下吗？什么版本下，有什们问题？
commit 53a042836063e965f8df9fc85bb32e8e46da8a05
调用api创建iptables规则后部分资源没有释放，导致下一张表的规则创建失败

**Comment by liudf0716** [comment]
@wp1411847064 能提个PR修复这个问题吗？你提到的commit是openssl相关的，应该跟iptables的api无关啊？
