### ISSUE TITLE
支持内核: 6.6.30，openwrt分支: 23.05-SNAPSHOT，Firewall4(nftables)吗？

### ISSUE THREAD

**Issue by mksss123** [liudf0716/apfree-wifidog#252]
最新版本是不是fw5了？我也不太确定，当时是不是只支持fw4

**Comment by liudf0716** [comment]
没有fw5。只有fw4跟fw3。目前社区已经不维护fw3了。 fw3是基于iptable那套搞得，fw4是基于nftable。apfree-wifidog目前社区都是最新版本

**Comment by liudf0716** [comment]
22.04， 23.05， master分支都是最新版本，再老的版本我不维护了。
